// Type declarations for @liquicode/jsonstor-couchdb
//
// Generated by jsonstor-docs/build/build-adapter-docs.js from docs/data/adapters.js.
// Edits here are erased by the next build.
//
// Documents are stored on a CouchDB server.

declare module '@liquicode/jsonstor-couchdb'
{

	//---------------------------------------------------------------------
	// The settings this adapter takes.

	export interface AdapterSettings
	{
		/** The name or address of the CouchDB server. */
		Server: string;
		/** The service port of the server. Defaults to `5984`. */
		Port?: number;
		/** Reach the server over `https` rather than `http`. There is no `TrustServerCertificate` beside it, because this adapter has no driver except the global `fetch`, which offers no supported way to relax certificate verification. See the notes. Defaults to `false`. */
		Encrypt?: boolean;
		/** The CouchDB database this storage reads and writes. It is the collection: one database holds one collection's documents. */
		DatabaseName: string;
		/** The document field which is the identifier. Its value becomes the CouchDB `_id`, so name the field a database you already have is keyed on. `IdField` is the former spelling and still works. Defaults to `"_id"`. */
		PrimaryKey?: string;
		/** Allow an update or a replacement to change the identifier. Off by default, so an operation which would move it is refused by name rather than silently discarded. Defaults to `false`. */
		PrimaryKeyMutable?: boolean;
		/** The field which stores the document. Empty means none, and then the document *is* the CouchDB document - which is what a database you already have looks like. See the notes. Defaults to `"jsonstor_document"`. */
		PayloadField?: string;
		/** The user to connect as. Empty means none, which only a CouchDB 2.x server with no administrator will accept. Defaults to `""`. */
		UserName?: string;
		/** That user's password. Empty means none. Defaults to `""`. */
		Password?: string;
	}


	//---------------------------------------------------------------------
	// The storage this adapter returns.
	//
	// Its members belong to jsonstor rather than to any adapter, so they are left open
	// here rather than restated - an adapter which described them would be describing
	// the storage interface, which is not its to describe.

	export interface Storage
	{
		[ MemberName: string ]: any;
	}


	//---------------------------------------------------------------------
	// The adapter itself. This is what `require()` returns, and what you hand to
	// `jsonstor.LoadPlugin()`.

	export interface StorageAdapter
	{
		/** `'jsonstor-couchdb'`. The package's bare name, which `Aliases` maps onto a prime. */
		AdapterName: string;
		AdapterDescription: string;
		GetAdapter( jsonstor: any, Settings: AdapterSettings ): Storage;
		/** This package's prime versions, each registering under its own name. */
		Adapters: StorageAdapter[];
		/** Every other name this package answers to, mapped to the prime it resolves to. */
		Aliases: { [ AliasName: string ]: string };
	}


	//---------------------------------------------------------------------
	// The default export is the adapter, and is what `require()` returns.

	const adapter: StorageAdapter;
	export default adapter;


	//---------------------------------------------------------------------
	// Named exports, matching src/jsonstor-couchdb.mjs one for one.

	export const AdapterName: string;
	export const AdapterDescription: string;
	export const GetAdapter: StorageAdapter[ 'GetAdapter' ];
	export const Adapters: StorageAdapter[ 'Adapters' ];
	export const Aliases: StorageAdapter[ 'Aliases' ];

}
